name: Scrape Hero Cards

on:
  workflow_dispatch:
  
  repository_dispatch:
    types:
      -webhook
      
  schedule:
    - cron: "0 1 * * 0"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0        
      - run: |
          npm install
          npm run scrape
          git config user.name hero-cards-bot
          git diff --quiet && git diff --staged --quiet || git commit -am "[bot] update Hero Cards database"
          git push origin main
  
